[package]
name = "npbudget"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ructe.workspace = true

[build-dependencies]
ructe.workspace = true

[workspace.dependencies]
ructe = "0.17.0"
